---
- name: Create Small Azure Dev VM
  hosts: localhost
  connection: local
  vars_files:
    - env.yml
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resourceGroup }}"
      location: southcentralus
      
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resourceGroup }}"
      name: "{{ vnet }}"
      address_prefixes: "10.250.0.0/16"
      
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resourceGroup }}"
      name: "{{ subnet }}"
      address_prefix: "10.250.1.0/24"
      virtual_network: "{{ vnet }}"
      
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resourceGroup }}"
      allocation_method: Static
      name: "{{ publicIp }}"
    register: output_ip_address
    
  - name: Show public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
      
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resourceGroup }}"
      name: "{{ nsg }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ resourceGroup }}"
      name: "{{ nic }}"
      virtual_network: "{{ vnet }}"
      subnet: "{{ subnet }}"
      public_ip_name: "{{ publicIp }}"
      security_group: "{{ nsg }}"
      
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resourceGroup }}"
      name: "{{ vm }}"
      vm_size: Standard_B1ls
      managed_disk_type: StandardSSD_LRS
      os_disk_size_gb: 30
      admin_username: "{{ admin_user }}"
      ssh_password_enabled: false
      ssh_public_keys:
          key_data: "{{ ssh_pubkey }}"
      network_interfaces: "{{ nic }}"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '8_1'
        version: '8.1.2020042900'
...